### ISSUE TITLE
Can not load css.map and js.map

### ISSUE THREAD

**Issue by minhcanhdn** [markstory/asset_compress#230]
I got Error 404 not found when i used  css and js have include map file. Please help.

**Comment by markstory** [comment]
Asset Compress doesn't currently generate map files.

**Comment by minhcanhdn** [comment]
What's it mean? That's mean is it can't use with css or js have the .map file or it's does not support now.

**Comment by markstory** [comment]
No the css and js files will work fine. Source map files are used by browsers to provide better debugging experiences when using minified or transpiled assets.

**Comment by minhcanhdn** [comment]
Thank bro,
I use this library, and when I use material.min.css, The browser display an error: material.min.css.map not found. How can i fix it? 
https://github.com/FezVrasta/bootstrap-material-design

**Comment by minhcanhdn** [comment]
I fixed it,
I just removed //# sourceMappingURL=material.min.js.map from material.min.css and js file is OK

Thank you for your help

**Comment by viplavsarkar** [comment]
for me it worked after I removed the last line(below) in the file **material.min.js**
# sourceMappingURL=material.min.js.map

**Comment by sebastienbarre** [comment]
FYI, the issue being, AssetCompress will take your JS files, aggregate them, and copy the result to a different `cache` directory. But your Javascript file still makes a relative reference to your source map via `sourceMappingURL`, as if the source map was co-located in the same folder as the Javascript library it is associated to. Since that library is now part of a bigger file, in a *different* directory, the browser can no longer find the source map next to that bigger file. If you really want to use source maps, you may need to copy it to the cache directory.
